// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omikgadqizchvxoygewn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9taWtnYWRxaXpjaHZ4b3lnZXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzAxMDksImV4cCI6MjA2ODk0NjEwOX0.6Qxd9kJ93op_8cfrzlqDzkNLjKCNLoVMcFonPKVKkmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});